{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ default .Release.Namespace .Values.namespace.name }}
  labels:
    {{- include "mspace.labels" . | nindent 4 }}
    {{- if .Values.namespace.podSecurity.enabled }}
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurity.enforce | quote }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurity.audit | quote }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurity.warn | quote }}
    {{- end }}
{{- end }}
