{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mspace.postgresName" . }}
  labels:
    {{- include "mspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "mspace.postgresName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mspace.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "mspace.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      serviceAccountName: {{ include "mspace.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: {{ include "mspace.postgresName" . }}
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgresql.persistence.storageClassName }}
        storageClassName: {{ .Values.postgresql.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size | quote }}
{{- end }}
