{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mspace.postgresName" . }}
  labels:
    {{- include "mspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    {{- include "mspace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
